#!/bin/sh
set -e
mkdir -p /usr/local/bin 2>/dev/null && ln -sf /var/usr/libexec/iphoneports-shell /usr/local/bin/iphoneports-shell 2>/dev/null || {
    if ! [ -h /var/usr ]; then
        if [ -d /var/jb ]; then
            if [ -d /var/jb/iphoneports ]; then
                cp -a /var/usr/* /var/jb/iphoneports
                rm -rf /var/usr
            else
                rm -rf /var/jb/iphoneports
                mv /var/usr /var/jb/iphoneports
            fi
            ln -s /var/jb/iphoneports /var/usr
            mkdir -p /var/jb/usr/bin
            ln -sf /var/jb/iphoneports/libexec/iphoneports-shell /var/jb/usr/bin
        else
            printf "!!!WARNING!!! rootfs is not writable but /var/jb doesn't exist, problems may arise!\n"
        fi
    fi
}
