case $- in
    *i*) ;;
    *) return ;;
esac

shopt -s checkwinsize
shopt -s no_empty_cmd_completion
shopt -s histappend

if [ "$EUID" = 0 ]; then
    PS1='\[\033[01;31m\]\h\[\033[01;34m\] \w \$\[\033[00m\] '
else
    PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'

for sh in /var/usr/etc/bash/bashrc.d/*; do
    [ -r "$sh" ] && . "$sh"
done
