[patch.crates-io]
rand_0_6_5 = { git = 'https://github.com/Un1q32/rand.git', package = 'rand', branch = '0.6.5' }
rand_os_0_1_1 = { git = 'https://github.com/Un1q32/rand.git', package = 'rand_os', branch = '0.6.5' }
system-interface_0_27_3 = { git = 'https://github.com/Un1q32/system-interface.git', package = 'system-interface', branch = '0.27.3' }
